/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoraimc;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author mara_
 */
public class Painel extends javax.swing.JFrame {

    /**
     * Creates new form Painel
     */
    public Painel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSituacaoImc = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        bntCalcularImc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULADORA DE IMC");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(106, 165, 88));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balanca.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 360));

        txtSituacaoImc.setBackground(new java.awt.Color(106, 165, 88));
        txtSituacaoImc.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        txtSituacaoImc.setForeground(new java.awt.Color(255, 255, 255));
        txtSituacaoImc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSituacaoImc.setBorder(null);
        txtSituacaoImc.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        txtSituacaoImc.setFocusable(false);
        jPanel1.add(txtSituacaoImc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 66, 220, 30));

        txtResultado.setBackground(new java.awt.Color(106, 165, 88));
        txtResultado.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(255, 255, 255));
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultado.setBorder(null);
        txtResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        txtResultado.setFocusable(false);
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 110, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 112, 200, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 390));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("C A L C U L A D O R A   D E   I  M C");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtAltura.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtAltura.setBorder(null);
        txtAltura.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        txtAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAlturaKeyPressed(evt);
            }
        });
        jPanel2.add(txtAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 280, 30));

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 280, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("A L T U R A   E M   M E T R O S");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 220, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setText("P E S O  E M  KG");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, -1));

        txtPeso.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPeso.setBorder(null);
        txtPeso.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        txtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesoKeyPressed(evt);
            }
        });
        jPanel2.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 280, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 280, 10));

        jButton1.setBackground(new java.awt.Color(106, 165, 88));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("L i m p a r");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 110, 40));

        bntCalcularImc.setBackground(new java.awt.Color(106, 165, 88));
        bntCalcularImc.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        bntCalcularImc.setForeground(new java.awt.Color(255, 255, 255));
        bntCalcularImc.setText("C a l c u l a r");
        bntCalcularImc.setBorder(null);
        bntCalcularImc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCalcularImcActionPerformed(evt);
            }
        });
        jPanel2.add(bntCalcularImc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 330, 390));

        setSize(new java.awt.Dimension(577, 435));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     */
    public void calcular () {
    float resultado = Float.parseFloat(txtPeso.getText().replaceAll(",",".")) / (Float.parseFloat(txtAltura.getText().replaceAll(",","."))
        * Float.parseFloat(txtAltura.getText().replaceAll(",","."))); // CÁLCULO DE IMC COM SUBSTITUIÇÃO DE VÍRGULA POR "PONTO"
    txtResultado.setText(String.valueOf(resultado));        // INSERIR RESULTADO DO IMC NA TE
    
    if (resultado < 18.5 ) {    //PREENCHIMENTO DO CAMPO SITUAÇÃO DO IMC
           
            txtSituacaoImc.setText(String.valueOf("Abaixo do peso"));
        }
            else if (resultado > 18.5 && resultado < 24.9) {
        
        txtSituacaoImc.setText(String.valueOf("Peso normal"));
        
             } else if (resultado > 24.9 && resultado < 29.9){
        
       txtSituacaoImc.setText(String.valueOf("Acima do peso"));
    
            } else if (resultado > 29.9 && resultado < 34.9) {
        
        txtSituacaoImc.setText(String.valueOf("Obesidade grau I"));
        
            }else if (resultado > 34.9 && resultado < 39.9) {
      
        txtSituacaoImc.setText(String.valueOf("Obesidade grau II"));
        
            } else if (resultado >=40) {
   
         txtSituacaoImc.setText(String.valueOf("Obesidade mórbida"));       
           } 
   
        


}
    private void bntCalcularImcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCalcularImcActionPerformed
        calcular();
    }//GEN-LAST:event_bntCalcularImcActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
txtResultado.setText(String.valueOf(""));
txtSituacaoImc.setText(String.valueOf(""));
    txtPeso.setText(String.valueOf(""));
    txtAltura.setText(String.valueOf(""));  // BOTÃO LIMPAR       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPesoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyPressed
       if (evt.getKeyCode () == KeyEvent.VK_ENTER) {
       txtAltura.requestFocus();
       } // PARA CLICAR ENTER E IR PARA OUTRO CAMPO
    }//GEN-LAST:event_txtPesoKeyPressed

    private void txtAlturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlturaKeyPressed
         if (evt.getKeyCode () == KeyEvent.VK_ENTER) {
       calcular();
       }// AO APERTAR O BOTÃO ENTER NO CAMPO ALTURA FARÁ O CÁLCULO
    }//GEN-LAST:event_txtAlturaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCalcularImc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtSituacaoImc;
    // End of variables declaration//GEN-END:variables
}
